from security.auth.models import (
    User,
    UserRole,
    Permission,
    UserCreate,
    UserUpdate,
    UserResponse,
    Token,
    TokenPayload,
    LoginRequest,
)
from security.auth.service import AuthService, PermissionService
from security.auth.dependencies import (
    get_auth_service,
    get_current_user_dep,
    get_current_active_user,
    require_permission,
    require_any_permission,
    require_all_permissions,
    require_role,
    RequireEvidenceRead,
    RequireEvidenceWrite,
    RequireFindingsRead,
    RequireFindingsWrite,
    RequireFindingsManage,
    RequireAnalysisRead,
    RequireAnalysisWrite,
    RequireAttackGraphRead,
    RequireAttackGraphWrite,
    RequireRemediationRead,
    RequireRemediationWrite,
    RequireRegressionRead,
    RequireRegressionWrite,
    RequirePoliciesRead,
    RequirePoliciesWrite,
    RequireBaselinesRead,
    RequireBaselinesWrite,
    RequireSeverityRead,
    RequireSeverityWrite,
    RequireAdminUsers,
    RequireAdminSystem,
    RequireAdmin,
    RequireAnalyst,
)
from security.auth.routes import router as auth_router