from engine import (
    adapters,
    adaptive,
    attack_surface,
    attacks,
    campaigns,
    chaining,
    coverage,
    discovery,
    execution,
    experiment,
    fleet,
    fuzzing,
    hypotheses,
    intelligence,
    model,
    mutation,
    orchestration,
    payloads,
    reconnaissance,
    sandbox,
    security,
    strategies,
    targets,
)
from engine.adaptive import AttackObservationRecord, CampaignState, ContextualMutator, EvidenceVariationGenerator, VariationSpec
from engine.attack_surface import AttackSurface, SurfaceFact
from engine.attacks import PLUGIN_REGISTRY, PluginRegistry, attack_plugin, discover_plugins
from engine.campaigns import (
    Campaign,
    CampaignBudget,
    CampaignConfig,
    CampaignEvidenceAggregator,
    CampaignManifest,
    CampaignRunner,
    CampaignStatus,
    CampaignStep,
    build_campaign_manifest,
    config_from_manifest,
    replay_campaign,
    verify_campaign_manifest,
)
from engine.chaining import CROSS_FAMILY_CHAIN, CampaignChain, CrossFamilyPlan, CrossFamilyStage, DependencyGraph
from engine.coverage import CoverageTracker, EffectivenessScore, score_result, summarize
from engine.discovery import AttackSurfaceDiscovery
from engine.execution import AttackContext, AttackExecutor, ExecutionEnvironment
from engine.experiment import Experiment, ExperimentRun, ExperimentScore, ExperimentSelector, IntelligenceReport, IntelligenceRunner
from engine.fleet import (
    AssuranceEngine,
    AssuranceReport,
    ChangeDetector,
    ChangeReport,
    CorrelationCluster,
    CorrelationEngine,
    FleetAnalytics,
    FleetMetrics,
    KnowledgeBase,
    KnowledgeLesson,
    PostureEngine,
    PostureSnapshot,
    RegressionIntelligence,
    RegressionTrend,
    RiskGraph,
    TargetSnapshot,
    TargetTwin,
)
from engine.fuzzing import AdaptiveFuzzer, FuzzRun, SeedManager
from engine.hypotheses import AttackHypothesis, HypothesisGenerator, HypothesisStatus, HypothesisTracker
from engine.intelligence import CampaignIntelligence
from engine.model.attack import (
    AttackObservation,
    AttackOutcome,
    AttackPolicy,
    AttackType,
    CapturePolicy,
    Provenance,
    TargetKind,
)
from engine.model.errors import (
    AttackCancelled,
    AttackTimeout,
    EngineError,
    ExecutionError,
    MockEvidenceRejected,
    TargetError,
)
from engine.model.execution import ExecutionResult, ExecutionStatus, ObservedExecution
from engine.model.plan import AttackDefinition, ExecutionPlan, ReplayManifest
from engine.orchestration import (
    AttackOrchestrator,
    AttackPlanner,
    ChainContext,
    RegressionCase,
    build_manifest,
    compare_regression,
    make_regression_case,
    replay_attack,
    verify_manifest,
)
from engine.reconnaissance import ReconnaissanceRunner, TargetProfile, profile_from_dict
from engine.sandbox import RateLimiter, Sandbox
from engine.security import FindingsGateway, FindingSink, InMemoryFindingSink, SecretsVault
from engine.strategies import (
    AttackCandidate,
    CoverageDrivenStrategy,
    ObservationDrivenStrategy,
    SelectionStrategy,
)
from engine.targets import RAGTargetConfig, TargetConfig, TargetRegistry, register_target

__version__ = "0.1.0"

__all__ = [
    "AttackCandidate",
    "AttackContext",
    "AttackDefinition",
    "AttackExecutor",
    "AttackHypothesis",
    "AttackObservation",
    "AttackObservationRecord",
    "AttackOrchestrator",
    "AttackOutcome",
    "AttackPlanner",
    "AttackPolicy",
    "AttackSurface",
    "AttackSurfaceDiscovery",
    "AttackTimeout",
    "AttackType",
    "CROSS_FAMILY_CHAIN",
    "Campaign",
    "CampaignBudget",
    "CampaignChain",
    "CampaignConfig",
    "CampaignEvidenceAggregator",
    "CampaignIntelligence",
    "CampaignManifest",
    "CampaignRunner",
    "CampaignState",
    "CampaignStatus",
    "CampaignStep",
    "CapturePolicy",
    "ChainContext",
    "ContextualMutator",
    "CoverageDrivenStrategy",
    "CoverageTracker",
    "CrossFamilyPlan",
    "CrossFamilyStage",
    "DependencyGraph",
    "EffectivenessScore",
    "EngineError",
    "EvidenceVariationGenerator",
    "ExecutionEnvironment",
    "ExecutionError",
    "ExecutionPlan",
    "ExecutionResult",
    "ExecutionStatus",
    "Experiment",
    "ExperimentRun",
    "ExperimentScore",
    "ExperimentSelector",
    "FindingsGateway",
    "FindingSink",
    "FleetAnalytics",
    "FleetMetrics",
    "FuzzRun",
    "HypothesisGenerator",
    "HypothesisStatus",
    "HypothesisTracker",
    "InMemoryFindingSink",
    "IntelligenceReport",
    "IntelligenceRunner",
    "KnowledgeBase",
    "KnowledgeLesson",
    "MockEvidenceRejected",
    "ObservationDrivenStrategy",
    "ObservedExecution",
    "PLUGIN_REGISTRY",
    "PluginRegistry",
    "PostureEngine",
    "PostureSnapshot",
    "Provenance",
    "RAGTargetConfig",
    "RateLimiter",
    "ReconnaissanceRunner",
    "RegressionCase",
    "RegressionIntelligence",
    "RegressionTrend",
    "ReplayManifest",
    "RiskGraph",
    "Sandbox",
    "SeedManager",
    "SecretsVault",
    "SelectionStrategy",
    "SurfaceFact",
    "TargetConfig",
    "TargetError",
    "TargetKind",
    "TargetProfile",
    "TargetRegistry",
    "TargetSnapshot",
    "TargetTwin",
    "VariationSpec",
    "adapters",
    "adaptive",
    "attack_plugin",
    "attack_surface",
    "attacks",
    "build_campaign_manifest",
    "build_manifest",
    "campaigns",
    "chaining",
    "compare_regression",
    "config_from_manifest",
    "coverage",
    "discover_plugins",
    "discovery",
    "execution",
    "experiment",
    "fleet",
    "fuzzing",
    "hypotheses",
    "intelligence",
    "make_regression_case",
    "model",
    "mutation",
    "orchestration",
    "payloads",
    "profile_from_dict",
    "reconnaissance",
    "replay_campaign",
    "sandbox",
    "score_result",
    "security",
    "strategies",
    "summarize",
    "targets",
    "verify_campaign_manifest",
    "verify_manifest",
]